# Generated by Django 6.0.2 on 2026-10-10 07:03

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'menu categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fssai_number', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/')),
                ('opens_at', models.TimeField(default=datetime.time(10, 0))),
                ('closes_at', models.TimeField(default=datetime.time(22, 0))),
                ('is_accepting_orders', models.BooleanField(default=True)),
                ('avg_prep_minutes', models.PositiveSmallIntegerField(default=30)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=6)),
                ('delivery_radius_km', models.DecimalField(decimal_places=1, default=Decimal('8'), max_digits=4)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('offer_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('offer_max_discount', models.PositiveIntegerField(default=0)),
                ('offer_min_order', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('offer_code', models.CharField(blank=True, max_length=30)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=12)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuisines', models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.cuisine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_veg', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/items/')),
                ('is_available', models.BooleanField(default=True)),
                ('packaging_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurants.menucategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant'),
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('placed', 'Placed'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('ready', 'Ready for pickup'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected by restaurant'), ('cancelled', 'Cancelled')], default='placed', max_length=20)),
                ('payment_method', models.CharField(choices=[('online', 'Online (UPI / Card)'), ('cod', 'Cash on delivery')], max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=60)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=60)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('packaging_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('gst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_code', models.CharField(blank=True, max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('delivery_address', models.JSONField(blank=True, default=dict)),
                ('delivery_lat', models.FloatField(blank=True, null=True)),
                ('delivery_lng', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_orders', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_veg', models.BooleanField(default=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packaging_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurants.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.restaurantorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='uniq_category_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['customer', '-created_at'], name='restaurants_custome_46d98d_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantorder',
            index=models.Index(fields=['restaurant', 'status'], name='restaurants_restaur_bc144d_idx'),
        ),
    ]
