# Generated by Django 6.0.2 on 2026-06-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='one_time_per_user',
            field=models.BooleanField(default=False),
        ),
    ]
