# Generated by Django 6.0.2 on 2026-06-17 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_coupon_one_time_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ('free_delivery_min', models.DecimalField(decimal_places=2, default=149, max_digits=6)),
                ('coupon_unlock_min', models.DecimalField(decimal_places=2, default=299, max_digits=6)),
                ('pass_price_monthly', models.DecimalField(decimal_places=2, default=999, max_digits=6)),
                ('pass_price_yearly', models.DecimalField(decimal_places=2, default=1499, max_digits=6)),
                ('free_delivery_cap_monthly', models.PositiveIntegerField(default=8)),
                ('free_delivery_cap_yearly', models.PositiveIntegerField(default=20)),
                ('free_delivery_cap', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Delivery Settings',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=999, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('free_deliveries_used', models.PositiveIntegerField(default=0)),
                ('last_reset_month', models.PositiveIntegerField(blank=True, null=True)),
                ('last_reset_year', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_cap', models.PositiveIntegerField(default=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pass', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
