# Generated by Django 6.0.2 on 2026-07-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_deliverysettings_deliverypass'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='base_delivery_km',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='per_km_charge',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
    ]
