# Generated by Django 6.0.2 on 2026-08-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_lat_address_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
