--
-- PostgreSQL database dump
--

\restrict IP8rkgbvOTyQbH8wi4cFP5eNX1sdKX196LbmIFfdbhka1AEgiNIHMBrGTheczSs

-- Dumped from database version 18.3 (Homebrew)
-- Dumped by pg_dump version 18.3 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: instantuser
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO instantuser;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    phone character varying(15) NOT NULL,
    address text
);


ALTER TABLE public.accounts_user OWNER TO instantuser;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO instantuser;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO instantuser;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO instantuser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO instantuser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO instantuser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_cart; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.cart_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.cart_cart OWNER TO instantuser;

--
-- Name: cart_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.cart_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_cartitem; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.cart_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT cart_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.cart_cartitem OWNER TO instantuser;

--
-- Name: cart_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.cart_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO instantuser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO instantuser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO instantuser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO instantuser;

--
-- Name: inventory_inventory; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.inventory_inventory (
    id bigint NOT NULL,
    total_stock integer NOT NULL,
    reserved_stock integer NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.inventory_inventory OWNER TO instantuser;

--
-- Name: inventory_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.inventory_inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: masters_advbanner; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.masters_advbanner (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.masters_advbanner OWNER TO instantuser;

--
-- Name: masters_advbanner_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.masters_advbanner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.masters_advbanner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: masters_banner; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.masters_banner (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    image character varying(100) NOT NULL,
    link character varying(200),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.masters_banner OWNER TO instantuser;

--
-- Name: masters_banner_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.masters_banner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.masters_banner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: masters_brand; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.masters_brand (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.masters_brand OWNER TO instantuser;

--
-- Name: masters_brand_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.masters_brand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.masters_brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: masters_category; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.masters_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    image character varying(100),
    is_active boolean NOT NULL
);


ALTER TABLE public.masters_category OWNER TO instantuser;

--
-- Name: masters_category_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.masters_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.masters_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: masters_subcategory; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.masters_subcategory (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.masters_subcategory OWNER TO instantuser;

--
-- Name: masters_subcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.masters_subcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.masters_subcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: masters_unit; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.masters_unit (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    short_name character varying(10) NOT NULL
);


ALTER TABLE public.masters_unit OWNER TO instantuser;

--
-- Name: masters_unit_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.masters_unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.masters_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.orders_order (
    id bigint NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    payment_status character varying(20) NOT NULL,
    coupon_id bigint,
    discount_amount numeric(10,2) NOT NULL,
    order_status character varying(20) NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.orders_order OWNER TO instantuser;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    total_price numeric(10,2) NOT NULL,
    CONSTRAINT orders_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.orders_orderitem OWNER TO instantuser;

--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    description text,
    image character varying(100),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    brand_id bigint,
    category_id bigint NOT NULL,
    subcategory_id bigint NOT NULL,
    unit_id bigint,
    discount_percent numeric(5,2) NOT NULL,
    unit_size numeric(10,2)
);


ALTER TABLE public.products_product OWNER TO instantuser;

--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: promotions_coupon; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.promotions_coupon (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    coupon_type character varying(20) NOT NULL,
    value numeric(10,2) NOT NULL,
    min_order_amount numeric(10,2) NOT NULL,
    active boolean NOT NULL,
    expires_at timestamp with time zone
);


ALTER TABLE public.promotions_coupon OWNER TO instantuser;

--
-- Name: promotions_coupon_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.promotions_coupon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotions_coupon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_inventory; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.stock_inventory (
    id bigint NOT NULL,
    total_stock integer NOT NULL,
    reserved_stock integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    low_stock_threshold integer NOT NULL,
    CONSTRAINT stock_inventory_low_stock_threshold_check CHECK ((low_stock_threshold >= 0)),
    CONSTRAINT stock_inventory_reserved_stock_bde9d413_check CHECK ((reserved_stock >= 0)),
    CONSTRAINT stock_inventory_total_stock_a4761793_check CHECK ((total_stock >= 0))
);


ALTER TABLE public.stock_inventory OWNER TO instantuser;

--
-- Name: stock_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.stock_inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_stockbatch; Type: TABLE; Schema: public; Owner: instantuser
--

CREATE TABLE public.stock_stockbatch (
    id bigint NOT NULL,
    batch_no character varying(50) NOT NULL,
    quantity integer NOT NULL,
    purchase_price numeric(10,2) NOT NULL,
    selling_price numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.stock_stockbatch OWNER TO instantuser;

--
-- Name: stock_stockbatch_id_seq; Type: SEQUENCE; Schema: public; Owner: instantuser
--

ALTER TABLE public.stock_stockbatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_stockbatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, phone, address) FROM stdin;
6	pbkdf2_sha256$1200000$9SxbsIeSIuuQTsxrOp0iAM$Ygk+wQAo4Zg7CH71qF5HL+5KkU7Ml+kp2NKDEA1yQJs=	\N	t	admin2			admin2@example.com	t	t	2026-03-06 10:14:09+05:30	ADMIN	9876543211	Kolkata
8	pbkdf2_sha256$1200000$XAb5SgmBHT7V1m4CB0GPzu$vsItnwrjULaDvegN9CfGNIosFtkgBgSrirMqCWRPL3M=	\N	f	customer1			custom1@example.com	f	t	2026-03-06 10:53:50.809634+05:30	CUSTOMER	9876543213	Kolkata
7	pbkdf2_sha256$1200000$5LhiYM0YYLBhCf69evw3ZD$8PEP3g07DmjtmSNfTt0TLCix8dMx+WE3yeVF/kRTzdY=	2026-03-25 10:38:48.302614+05:30	t	admin3			admin3@example.com	t	t	2026-03-06 10:22:58+05:30	ADMIN	9876543212	Kolkata
1	pbkdf2_sha256$1200000$b4ukOzwwHi8DQkm6SlSaKz$1xMggZRJ4JAzCg9zERTXOPn+9IpBhgzvrwvjdwA9V+k=	2026-03-25 10:39:15.062262+05:30	t	Supperuser			sylmondal@gmail.com	t	t	2026-02-28 17:14:42+05:30	ADMIN	8670853699	
11	pbkdf2_sha256$1200000$tufPtjSaUPOnXN8hmXSFhd$0NRzHuzux8fLE6xFKQReuqJWAOh0ktsmIIR6QPVWgw0=	\N	f	Papri			papri@gmail.com	f	t	2026-03-27 13:57:27.98113+05:30	CUSTOMER	9876543210	Kolkata
10	pbkdf2_sha256$1200000$h6lHwaVzsWRSTwnVPgFIXx$cDfHM5Y77zELwjLft1hX8xhJSMqS2kOg+MUe2d4Y2i0=	\N	f	sylvester	Sylvester	Mondal	sylmondal@example.com	f	t	2026-03-27 12:53:30+05:30	CUSTOMER	9732485965	Kolkata
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add brand	7	add_brand
26	Can change brand	7	change_brand
27	Can delete brand	7	delete_brand
28	Can view brand	7	view_brand
29	Can add unit	10	add_unit
30	Can change unit	10	change_unit
31	Can delete unit	10	delete_unit
32	Can view unit	10	view_unit
33	Can add sub category	9	add_subcategory
34	Can change sub category	9	change_subcategory
35	Can delete sub category	9	delete_subcategory
36	Can view sub category	9	view_subcategory
37	Can add category	8	add_category
38	Can change category	8	change_category
39	Can delete category	8	delete_category
40	Can view category	8	view_category
41	Can add product	11	add_product
42	Can change product	11	change_product
43	Can delete product	11	delete_product
44	Can view product	11	view_product
45	Can add cart	12	add_cart
46	Can change cart	12	change_cart
47	Can delete cart	12	delete_cart
48	Can view cart	12	view_cart
49	Can add cart item	13	add_cartitem
50	Can change cart item	13	change_cartitem
51	Can delete cart item	13	delete_cartitem
52	Can view cart item	13	view_cartitem
53	Can add order item	15	add_orderitem
54	Can change order item	15	change_orderitem
55	Can delete order item	15	delete_orderitem
56	Can view order item	15	view_orderitem
57	Can add order	14	add_order
58	Can change order	14	change_order
59	Can delete order	14	delete_order
60	Can view order	14	view_order
61	Can add inventory	16	add_inventory
62	Can change inventory	16	change_inventory
63	Can delete inventory	16	delete_inventory
64	Can view inventory	16	view_inventory
65	Can add inventory	17	add_inventory
66	Can change inventory	17	change_inventory
67	Can delete inventory	17	delete_inventory
68	Can view inventory	17	view_inventory
69	Can add coupon	18	add_coupon
70	Can change coupon	18	change_coupon
71	Can delete coupon	18	delete_coupon
72	Can view coupon	18	view_coupon
73	Can add stock batch	19	add_stockbatch
74	Can change stock batch	19	change_stockbatch
75	Can delete stock batch	19	delete_stockbatch
76	Can view stock batch	19	view_stockbatch
77	Can add banner	20	add_banner
78	Can change banner	20	change_banner
79	Can delete banner	20	delete_banner
80	Can view banner	20	view_banner
81	Can add adv banner	21	add_advbanner
82	Can change adv banner	21	change_advbanner
83	Can delete adv banner	21	delete_advbanner
84	Can view adv banner	21	view_advbanner
\.


--
-- Data for Name: cart_cart; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.cart_cart (id, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: cart_cartitem; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.cart_cartitem (id, quantity, cart_id, product_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-02-28 20:20:20.277124+05:30	1	Amul	1	[{"added": {}}]	7	1
2	2026-02-28 20:20:52.836163+05:30	2	Dairy Milk	1	[{"added": {}}]	7	1
3	2026-02-28 20:22:54.656489+05:30	1	Electronics	1	[{"added": {}}]	8	1
4	2026-02-28 20:23:24.654964+05:30	2	Fruits & Vegetables	1	[{"added": {}}]	8	1
5	2026-02-28 20:23:30.553834+05:30	3	Dairy & Eggs	1	[{"added": {}}]	8	1
6	2026-02-28 20:23:35.812535+05:30	4	Beverages	1	[{"added": {}}]	8	1
7	2026-02-28 20:23:42.543888+05:30	5	Snacks & Packaged Food	1	[{"added": {}}]	8	1
8	2026-02-28 20:25:28.938988+05:30	1	Fruits & Vegetables - Fresh Fruits	1	[{"added": {}}]	9	1
9	2026-02-28 20:25:39.2044+05:30	2	Fruits & Vegetables - Organic Fruits	1	[{"added": {}}]	9	1
10	2026-02-28 20:25:49.031197+05:30	3	Dairy & Eggs - Milk	1	[{"added": {}}]	9	1
11	2026-02-28 20:25:56.787823+05:30	4	Dairy & Eggs - Cheese	1	[{"added": {}}]	9	1
12	2026-02-28 20:26:09.342096+05:30	5	Dairy & Eggs - Yogurt & Curd	1	[{"added": {}}]	9	1
13	2026-02-28 20:26:26.083947+05:30	6	Beverages - Juices & Smoothies	1	[{"added": {}}]	9	1
14	2026-02-28 20:26:34.468874+05:30	7	Beverages - Soft Drinks	1	[{"added": {}}]	9	1
15	2026-02-28 20:26:43.437817+05:30	8	Snacks & Packaged Food - Chips & Crisps	1	[{"added": {}}]	9	1
16	2026-02-28 20:26:52.776323+05:30	9	Snacks & Packaged Food - Cookies & Biscuits	1	[{"added": {}}]	9	1
17	2026-02-28 20:27:33.751042+05:30	1	Kilogram	1	[{"added": {}}]	10	1
18	2026-02-28 20:27:41.801219+05:30	2	Gram	1	[{"added": {}}]	10	1
19	2026-02-28 20:27:48.33674+05:30	3	Liter	1	[{"added": {}}]	10	1
20	2026-02-28 20:27:57.284568+05:30	4	Milliliter	1	[{"added": {}}]	10	1
21	2026-02-28 20:28:15.01809+05:30	5	Piece	1	[{"added": {}}]	10	1
22	2026-02-28 20:31:15.462014+05:30	1	Apple	1	[{"added": {}}]	11	1
23	2026-02-28 20:32:05.115081+05:30	2	Banana	1	[{"added": {}}]	11	1
24	2026-02-28 20:32:43.566957+05:30	3	Whole Milk	1	[{"added": {}}]	11	1
25	2026-02-28 20:33:18.167128+05:30	4	Cheddar Cheese	1	[{"added": {}}]	11	1
26	2026-02-28 20:34:10.330113+05:30	5	Orange Juice	1	[{"added": {}}]	11	1
27	2026-02-28 20:35:09.03627+05:30	1	SAVE50	1	[{"added": {}}]	18	1
28	2026-02-28 20:35:38.190967+05:30	5	Orange Juice Inventory	2	[{"changed": {"fields": ["Total stock"]}}]	17	1
29	2026-02-28 20:35:46.841921+05:30	4	Cheddar Cheese Inventory	2	[{"changed": {"fields": ["Total stock"]}}]	17	1
30	2026-02-28 20:35:52.109634+05:30	3	Whole Milk Inventory	2	[{"changed": {"fields": ["Total stock"]}}]	17	1
31	2026-02-28 20:36:00.404488+05:30	2	Banana Inventory	2	[{"changed": {"fields": ["Total stock"]}}]	17	1
32	2026-02-28 20:36:10.355251+05:30	1	Apple Inventory	2	[{"changed": {"fields": ["Total stock"]}}]	17	1
33	2026-02-28 20:37:30.869456+05:30	5	Orange Juice Inventory	2	[{"changed": {"fields": ["Total stock"]}}]	17	1
34	2026-02-28 20:37:47.921322+05:30	5	Orange Juice Inventory	2	[{"changed": {"fields": ["Total stock"]}}]	17	1
35	2026-02-28 20:37:54.704705+05:30	5	Orange Juice Inventory	2	[{"changed": {"fields": ["Total stock"]}}]	17	1
36	2026-03-01 13:15:27.047695+05:30	1	Supperuser	2	[{"changed": {"fields": ["Password", "Role", "Phone"]}}]	6	1
43	2026-03-06 10:23:31.4388+05:30	6	admin2	2	[{"changed": {"fields": ["Superuser status"]}}]	6	1
44	2026-03-06 10:24:01.143344+05:30	7	admin3	2	[{"changed": {"fields": ["Superuser status"]}}]	6	1
45	2026-03-06 11:28:19.215319+05:30	8	Kg	3		8	1
46	2026-03-06 11:28:19.215344+05:30	7	Milk	3		8	1
47	2026-03-06 12:20:16.207616+05:30	8	Amul Butter	3		11	1
48	2026-03-06 12:20:16.207715+05:30	7	Amul Butter	3		11	1
49	2026-03-06 12:20:41.780736+05:30	9	Amul Butter	3		11	1
50	2026-03-06 16:38:15.725842+05:30	10	Test 2	3		8	1
51	2026-03-06 16:38:15.725958+05:30	9	Test	3		8	1
52	2026-03-09 17:10:53.253896+05:30	3	Dairy - Milk	2	[{"changed": {"fields": ["Category"]}}]	9	1
53	2026-03-13 16:42:53.008241+05:30	13	Kg	3		10	1
54	2026-03-13 16:42:53.008396+05:30	12	Kg	3		10	1
55	2026-03-13 16:45:07.626686+05:30	15	Kg	3		10	1
56	2026-03-13 16:45:07.626828+05:30	14	Kg	3		10	1
57	2026-03-13 16:45:34.06455+05:30	16	Kg	3		10	1
58	2026-03-13 16:46:07.571774+05:30	17	Kg	3		10	1
59	2026-03-13 16:46:44.353545+05:30	18	Kg	3		10	1
60	2026-03-13 16:48:41.951178+05:30	19	Kgdd	3		10	1
61	2026-03-13 16:51:18.055376+05:30	20	Kilogram	3		10	1
62	2026-03-13 17:09:54.134456+05:30	25	Kildddogramgg	2	[{"changed": {"fields": ["Short name"]}}]	10	1
63	2026-03-25 12:33:41.156436+05:30	10	Test Brand. s	2	[]	7	1
64	2026-03-25 13:31:36.03986+05:30	10	Dairy sdff - Soft Drinks	2	[{"changed": {"fields": ["Category"]}}]	9	1
65	2026-03-26 11:01:13.413857+05:30	3	Amul Butter - Batch BATCH002	2	[{"changed": {"fields": ["Batch no"]}}]	19	1
66	2026-03-26 11:57:34.133764+05:30	2	Amul Butter - Batch BATCH001	2	[{"changed": {"fields": ["Quantity"]}}]	19	1
67	2026-03-26 12:40:39.84875+05:30	18	Test Inventory	3		17	1
68	2026-03-26 12:40:39.848874+05:30	13	Amul Butter Inventory	3		17	1
69	2026-03-26 12:40:39.848935+05:30	5	Orange Juice Inventory	3		17	1
70	2026-03-26 12:40:39.848989+05:30	4	Cheddar Cheese Inventory	3		17	1
71	2026-03-26 12:40:39.849042+05:30	3	Whole Milk Inventory	3		17	1
72	2026-03-26 12:46:24.979596+05:30	7	Amul Butter - Batch BATCH001	3		19	1
73	2026-03-26 12:46:24.979659+05:30	6	Whole Milk - Batch BATCHNO1	3		19	1
74	2026-03-26 12:47:20.878974+05:30	19	Test Inventory	2	[{"changed": {"fields": ["Reserved stock"]}}]	17	1
75	2026-03-26 12:47:30.214657+05:30	19	Test Inventory	2	[{"changed": {"fields": ["Reserved stock"]}}]	17	1
76	2026-03-26 15:38:57.954967+05:30	20	Whole Milk Inventory	2	[{"changed": {"fields": ["Reserved stock"]}}]	17	1
77	2026-03-26 16:20:19.266859+05:30	6	Order #6 - admin3@example.com	3		14	1
78	2026-03-26 16:20:19.266943+05:30	5	Order #5 - admin3@example.com	3		14	1
79	2026-03-26 16:20:19.266976+05:30	3	Order #3 - admin3@example.com	3		14	1
80	2026-03-26 16:20:19.267005+05:30	2	Order #2 - admin3@example.com	3		14	1
81	2026-03-26 16:26:01.06749+05:30	7	Order #7 - admin3@example.com	3		14	1
82	2026-03-26 16:35:23.805969+05:30	12	Order #12 - admin3@example.com	3		14	1
83	2026-03-26 16:35:23.806044+05:30	11	Order #11 - admin3@example.com	3		14	1
84	2026-03-26 16:35:23.806074+05:30	10	Order #10 - admin3@example.com	3		14	1
85	2026-03-26 16:35:23.806101+05:30	9	Order #9 - admin3@example.com	3		14	1
86	2026-03-26 17:48:06.224544+05:30	15	Order #15 - admin3@example.com	3		14	1
87	2026-03-26 17:48:06.22461+05:30	14	Order #14 - admin3@example.com	3		14	1
88	2026-03-26 17:48:06.224643+05:30	13	Order #13 - admin3@example.com	3		14	1
89	2026-03-26 17:51:30.458627+05:30	16	Order #16 - admin3@example.com	2	[{"changed": {"fields": ["Order status"]}}]	14	1
90	2026-03-26 17:51:42.125164+05:30	16	Order #16 - admin3@example.com	2	[{"changed": {"fields": ["Order status"]}}]	14	1
91	2026-03-27 09:43:16.119987+05:30	16	Order #16 - admin3@example.com	2	[{"changed": {"fields": ["Order status"]}}]	14	1
92	2026-03-27 09:59:58.989278+05:30	15	Test	3		11	1
93	2026-03-27 10:20:05.299301+05:30	3	Amul Gold Milk	2	[{"changed": {"fields": ["Name", "Category", "Brand", "Description", "Image"]}}]	11	1
94	2026-03-27 10:21:02.359963+05:30	3	Amul Gold Milk	2	[{"changed": {"fields": ["Price"]}}]	11	1
95	2026-03-27 10:23:42.575988+05:30	4	Amul Slice Cheese	2	[{"changed": {"fields": ["Name", "Category", "Brand", "Price", "Description", "Image"]}}]	11	1
96	2026-03-27 10:25:32.545009+05:30	5	Orange Juice	2	[{"changed": {"fields": ["Subcategory", "Price", "Image"]}}]	11	1
97	2026-03-27 10:29:42.611067+05:30	10	Amul Butter	2	[{"changed": {"fields": ["Unit", "Price", "Discount percent", "Description", "Image"]}}]	11	1
98	2026-03-27 10:29:56.68288+05:30	5	Dairy - Yogurt & Curd	2	[{"changed": {"fields": ["Category"]}}]	9	1
99	2026-03-27 10:30:03.718434+05:30	4	Dairy - Cheese	2	[{"changed": {"fields": ["Category"]}}]	9	1
100	2026-03-27 12:37:17.342754+05:30	9	Sylvester	1	[{"added": {}}]	6	1
101	2026-03-27 12:51:53.619098+05:30	9	Sylvester	3		6	1
102	2026-03-31 12:26:44.596539+05:30	5	Orange Juice	2	[{"changed": {"fields": ["Brand"]}}]	11	1
103	2026-03-31 12:27:02.906631+05:30	5	Orange Juice	2	[{"changed": {"fields": ["Brand"]}}]	11	1
104	2026-03-31 15:00:05.967875+05:30	5	Orange Juice	2	[{"changed": {"fields": ["Image"]}}]	11	1
105	2026-03-31 15:01:15.414961+05:30	16	Test Product	2	[{"changed": {"fields": ["Image"]}}]	11	1
106	2026-04-01 12:25:58.28502+05:30	10	sylvester	2	[{"changed": {"fields": ["First name", "Last name"]}}]	6	1
107	2026-04-02 11:29:50.914945+05:30	16	Test Product	2	[{"changed": {"fields": ["Unit size"]}}]	11	1
108	2026-04-02 11:29:59.286662+05:30	10	Amul Butter	2	[{"changed": {"fields": ["Unit size"]}}]	11	1
109	2026-04-02 11:30:18.440242+05:30	5	Orange Juice	2	[{"changed": {"fields": ["Unit size"]}}]	11	1
110	2026-04-02 11:30:25.374237+05:30	4	Amul Slice Cheese	2	[{"changed": {"fields": ["Unit size"]}}]	11	1
111	2026-04-02 11:30:33.574569+05:30	3	Amul Gold Milk	2	[{"changed": {"fields": ["Unit size"]}}]	11	1
112	2026-04-02 13:26:31.662425+05:30	22	Amul Butter Inventory	2	[{"changed": {"fields": ["Reserved stock"]}}]	17	1
113	2026-04-02 13:27:41.49956+05:30	25	Amul Cow Ghee Inventory	2	[{"changed": {"fields": ["Total stock", "Reserved stock"]}}]	17	1
114	2026-04-02 15:59:54.511761+05:30	2	Top Adv	2	[{"changed": {"fields": ["Title", "Image"]}}]	20	1
115	2026-04-02 16:00:17.037969+05:30	1	Bottom Adv	2	[{"changed": {"fields": ["Title", "Image"]}}]	20	1
116	2026-04-02 16:39:14.00461+05:30	2	Top Adv	2	[{"changed": {"fields": ["Image"]}}]	20	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	masters	brand
8	masters	category
9	masters	subcategory
10	masters	unit
11	products	product
12	cart	cart
13	cart	cartitem
14	orders	order
15	orders	orderitem
16	inventory	inventory
17	stock	inventory
18	promotions	coupon
19	stock	stockbatch
20	masters	banner
21	masters	advbanner
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-28 17:12:01.66443+05:30
2	contenttypes	0002_remove_content_type_name	2026-02-28 17:12:01.667937+05:30
3	auth	0001_initial	2026-02-28 17:12:01.689796+05:30
4	auth	0002_alter_permission_name_max_length	2026-02-28 17:12:01.692189+05:30
5	auth	0003_alter_user_email_max_length	2026-02-28 17:12:01.694174+05:30
6	auth	0004_alter_user_username_opts	2026-02-28 17:12:01.696114+05:30
7	auth	0005_alter_user_last_login_null	2026-02-28 17:12:01.697899+05:30
8	auth	0006_require_contenttypes_0002	2026-02-28 17:12:01.700794+05:30
9	auth	0007_alter_validators_add_error_messages	2026-02-28 17:12:01.702614+05:30
10	auth	0008_alter_user_username_max_length	2026-02-28 17:12:01.704339+05:30
11	auth	0009_alter_user_last_name_max_length	2026-02-28 17:12:01.706431+05:30
12	auth	0010_alter_group_name_max_length	2026-02-28 17:12:01.709445+05:30
13	auth	0011_update_proxy_permissions	2026-02-28 17:12:01.71116+05:30
14	auth	0012_alter_user_first_name_max_length	2026-02-28 17:12:01.712997+05:30
15	accounts	0001_initial	2026-02-28 17:12:01.736427+05:30
16	admin	0001_initial	2026-02-28 17:12:01.745506+05:30
17	admin	0002_logentry_remove_auto_add	2026-02-28 17:12:01.748291+05:30
18	admin	0003_logentry_add_action_flag_choices	2026-02-28 17:12:01.750969+05:30
19	sessions	0001_initial	2026-02-28 17:12:01.755721+05:30
20	masters	0001_initial	2026-02-28 17:19:49.167741+05:30
21	products	0001_initial	2026-02-28 17:26:20.423628+05:30
22	cart	0001_initial	2026-02-28 17:31:06.535987+05:30
23	orders	0001_initial	2026-02-28 17:33:19.01084+05:30
24	products	0002_product_discount_percent	2026-02-28 17:37:10.301111+05:30
25	products	0003_remove_product_stock	2026-02-28 17:44:34.896666+05:30
26	inventory	0001_initial	2026-02-28 17:44:34.910506+05:30
29	orders	0002_remove_order_status_order_payment_status	2026-02-28 18:21:58.327032+05:30
30	promotions	0001_initial	2026-02-28 19:54:01.01034+05:30
31	orders	0003_order_coupon_order_discount_amount_and_more	2026-03-06 09:59:40.161718+05:30
32	products	0004_alter_product_brand_alter_product_name	2026-03-06 13:06:36.143099+05:30
34	stock	0001_initial	2026-03-06 13:18:20.290322+05:30
35	stock	0002_stockbatch	2026-03-06 13:22:55.757881+05:30
36	masters	0002_alter_subcategory_category_alter_subcategory_name	2026-03-13 16:55:28.435865+05:30
37	orders	0004_orderitem_total_price	2026-03-26 16:25:52.420021+05:30
38	products	0005_product_unit_size_alter_product_image	2026-04-02 10:18:52.456936+05:30
39	masters	0003_banner	2026-04-02 15:19:15.423822+05:30
40	masters	0004_advbanner	2026-04-02 16:45:17.30439+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
tcstg391psol9vppvi01212vgnvu3t25	.eJxVjEEOwiAQRe_C2hBgKBWX7nsGMsOMUjU0Ke3KeHdD0oVu_3vvv1XCfStpb7KmmdVFWXX63QjzU2oH_MB6X3Re6rbOpLuiD9r0tLC8rof7d1CwlV57BkQaIAwuEwOI8Y4hnq2IRXIQbw5zdOzFyBhHww6CpWwpAMVA6vMF8bg4GA:1vyN6f:zQ8QDOrQYoDiq5PQo5DvA_YJa89w1lGWDco9TOEE5_8	2026-03-20 10:18:09.747774+05:30
8huz0zo45ugxfkyhvxqgtzy9p51oigit	.eJxVjEEOwiAQRe_C2hBgKBWX7nsGMsOMUjU0Ke3KeHdD0oVu_3vvv1XCfStpb7KmmdVFWXX63QjzU2oH_MB6X3Re6rbOpLuiD9r0tLC8rof7d1CwlV57BkQaIAwuEwOI8Y4hnq2IRXIQbw5zdOzFyBhHww6CpWwpAMVA6vMF8bg4GA:1w5GUV:_TigNZOnW-Afeep3JPfrwqMmELNhVdJGY6cdNMrcLmM	2026-04-08 10:39:15.063675+05:30
\.


--
-- Data for Name: inventory_inventory; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.inventory_inventory (id, total_stock, reserved_stock, product_id) FROM stdin;
\.


--
-- Data for Name: masters_advbanner; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.masters_advbanner (id, image, is_active, created_at, updated_at) FROM stdin;
1	advbanners/banner.jpg	t	2026-04-02 17:34:40.347373+05:30	2026-04-02 17:34:40.347424+05:30
\.


--
-- Data for Name: masters_banner; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.masters_banner (id, title, image, link, is_active, created_at, updated_at) FROM stdin;
1	Bottom Adv	banners/banner-mobile.jpg	\N	t	2026-04-02 15:57:33.010811+05:30	2026-04-02 16:00:17.036351+05:30
2	Top Adv	banners/banner-mobile_Xx0whYD.jpg	\N	t	2026-04-02 15:57:38.967417+05:30	2026-04-02 16:39:14.001959+05:30
\.


--
-- Data for Name: masters_brand; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.masters_brand (id, name, is_active) FROM stdin;
2	Dairy Milk	t
4	Amul	t
\.


--
-- Data for Name: masters_category; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.masters_category (id, name, image, is_active) FROM stdin;
3	Dairy & Eggs		t
4	Beverages		t
5	Snacks & Packaged Food		t
6	Dairy		t
2	Fruits & Vegetables		t
16	Dairy sdff		t
\.


--
-- Data for Name: masters_subcategory; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.masters_subcategory (id, name, category_id) FROM stdin;
6	Juices & Smoothies	4
7	Soft Drinks	4
8	Chips & Crisps	5
9	Cookies & Biscuits	5
11	Mango	2
3	Milk	6
10	Soft Drinks	4
5	Yogurt & Curd	6
4	Cheese	6
\.


--
-- Data for Name: masters_unit; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.masters_unit (id, name, short_name) FROM stdin;
1	Kilogram	kg
2	Gram	g
3	Liter	l
4	Milliliter	ml
5	Piece	piece
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.orders_order (id, total_amount, created_at, user_id, payment_status, coupon_id, discount_amount, order_status, updated_at) FROM stdin;
16	60.00	2026-03-26 17:49:20.944096+05:30	7	PENDING	\N	0.00	SHIPPED	2026-03-27 09:43:50.547463+05:30
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.orders_orderitem (id, quantity, price, order_id, product_id, total_price) FROM stdin;
15	1	60.00	16	5	60.00
\.


--
-- Data for Name: products_product; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.products_product (id, name, price, description, image, is_active, created_at, brand_id, category_id, subcategory_id, unit_id, discount_percent, unit_size) FROM stdin;
17	Amul Cow Ghee	100.00	Amul Cow Ghee – Pure & Aromatic Traditional Ghee\r\n\r\nAmul Cow Ghee is a premium quality clarified butter made from fresh cow’s milk using traditional methods. Known for its rich aroma, golden color, and authentic taste, it enhances the flavor of every dish—from daily meals to festive delicacies.\r\n\r\nPrepared with care and high hygiene standards, Amul Cow Ghee is packed with natural goodness and essential nutrients. It is ideal for cooking, frying, and as a topping for rotis, rice, and sweets. Its long shelf life and consistent quality make it a trusted choice in every kitchen.\r\n\r\nKey Features:\r\n\r\nMade from pure cow’s milk\r\nRich aroma and authentic taste\r\nEnhances flavor of food\r\nIdeal for cooking, frying, and garnishing\r\nTrusted brand with consistent quality	products/media/Amul_butter.png	t	2026-04-02 10:55:54.649569+05:30	4	16	9	2	4.00	500.00
16	Test Product	10.00	TEst entry	products/media/orange_juice_76Ub4oA.jpg	t	2026-03-31 12:28:38.449881+05:30	\N	2	11	1	0.00	1.00
10	Amul Butter	285.00	Amul Butter 500G	products/Amul_Butter.jpeg	t	2026-03-06 12:24:45.257949+05:30	2	6	4	1	-0.01	500.00
5	Orange Juice	94.00	100% natural orange juice	products/media/orange_juice.jpg	t	2026-02-28 20:34:10.327213+05:30	\N	4	10	3	0.00	750.00
4	Amul Slice Cheese	75.00	Amul Slice Cheese	products/amul_s_cheese.jpeg	t	2026-02-28 20:33:18.162561+05:30	4	6	4	1	0.00	49.99
3	Amul Gold Milk	83.00	Amul Gold 1L Packet	products/amul-gold-milk.png	t	2026-02-28 20:32:43.563973+05:30	4	6	3	3	0.00	499.98
\.


--
-- Data for Name: promotions_coupon; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.promotions_coupon (id, code, coupon_type, value, min_order_amount, active, expires_at) FROM stdin;
1	SAVE50	FIXED	15.00	2.00	t	2026-09-01 20:35:00+05:30
\.


--
-- Data for Name: stock_inventory; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.stock_inventory (id, total_stock, reserved_stock, updated_at, product_id, low_stock_threshold) FROM stdin;
20	4	1	2026-03-26 16:33:27.951557+05:30	3	5
21	9	0	2026-03-26 16:35:38.202906+05:30	4	5
23	18	0	2026-03-26 17:49:20.946684+05:30	5	5
24	0	0	2026-03-31 12:28:38.454924+05:30	16	5
22	20	5	2026-04-02 13:26:31.655773+05:30	10	5
25	10	5	2026-04-02 13:27:41.498062+05:30	17	5
\.


--
-- Data for Name: stock_stockbatch; Type: TABLE DATA; Schema: public; Owner: instantuser
--

COPY public.stock_stockbatch (id, batch_no, quantity, purchase_price, selling_price, created_at, product_id) FROM stdin;
9	BATCH NO 0101	20	45.00	55.00	2026-03-26 12:48:44.789951+05:30	3
10	BATCH NO 1010	15	77.00	85.00	2026-03-26 12:49:16.14438+05:30	4
11	BATCH NO A01	20	59.00	59.00	2026-03-26 12:49:53.206363+05:30	10
12	BATCH NO OJ01	20	40.00	60.00	2026-03-26 12:50:29.540063+05:30	5
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 11, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 84, true);


--
-- Name: cart_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.cart_cart_id_seq', 1, false);


--
-- Name: cart_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.cart_cartitem_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 116, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 21, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 40, true);


--
-- Name: inventory_inventory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.inventory_inventory_id_seq', 1, false);


--
-- Name: masters_advbanner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.masters_advbanner_id_seq', 1, true);


--
-- Name: masters_banner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.masters_banner_id_seq', 2, true);


--
-- Name: masters_brand_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.masters_brand_id_seq', 11, true);


--
-- Name: masters_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.masters_category_id_seq', 16, true);


--
-- Name: masters_subcategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.masters_subcategory_id_seq', 15, true);


--
-- Name: masters_unit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.masters_unit_id_seq', 28, true);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 16, true);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 15, true);


--
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.products_product_id_seq', 17, true);


--
-- Name: promotions_coupon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.promotions_coupon_id_seq', 1, true);


--
-- Name: stock_inventory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.stock_inventory_id_seq', 25, true);


--
-- Name: stock_stockbatch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: instantuser
--

SELECT pg_catalog.setval('public.stock_stockbatch_id_seq', 12, true);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_phone_key; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_phone_key UNIQUE (phone);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: cart_cart cart_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_pkey PRIMARY KEY (id);


--
-- Name: cart_cart cart_cart_user_id_key; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_user_id_key UNIQUE (user_id);


--
-- Name: cart_cartitem cart_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: inventory_inventory inventory_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.inventory_inventory
    ADD CONSTRAINT inventory_inventory_pkey PRIMARY KEY (id);


--
-- Name: inventory_inventory inventory_inventory_product_id_key; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.inventory_inventory
    ADD CONSTRAINT inventory_inventory_product_id_key UNIQUE (product_id);


--
-- Name: masters_advbanner masters_advbanner_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.masters_advbanner
    ADD CONSTRAINT masters_advbanner_pkey PRIMARY KEY (id);


--
-- Name: masters_banner masters_banner_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.masters_banner
    ADD CONSTRAINT masters_banner_pkey PRIMARY KEY (id);


--
-- Name: masters_brand masters_brand_name_key; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.masters_brand
    ADD CONSTRAINT masters_brand_name_key UNIQUE (name);


--
-- Name: masters_brand masters_brand_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.masters_brand
    ADD CONSTRAINT masters_brand_pkey PRIMARY KEY (id);


--
-- Name: masters_category masters_category_name_key; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.masters_category
    ADD CONSTRAINT masters_category_name_key UNIQUE (name);


--
-- Name: masters_category masters_category_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.masters_category
    ADD CONSTRAINT masters_category_pkey PRIMARY KEY (id);


--
-- Name: masters_subcategory masters_subcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.masters_subcategory
    ADD CONSTRAINT masters_subcategory_pkey PRIMARY KEY (id);


--
-- Name: masters_unit masters_unit_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.masters_unit
    ADD CONSTRAINT masters_unit_pkey PRIMARY KEY (id);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_name_fa23bcd2_uniq; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_name_fa23bcd2_uniq UNIQUE (name);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: promotions_coupon promotions_coupon_code_key; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.promotions_coupon
    ADD CONSTRAINT promotions_coupon_code_key UNIQUE (code);


--
-- Name: promotions_coupon promotions_coupon_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.promotions_coupon
    ADD CONSTRAINT promotions_coupon_pkey PRIMARY KEY (id);


--
-- Name: stock_inventory stock_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.stock_inventory
    ADD CONSTRAINT stock_inventory_pkey PRIMARY KEY (id);


--
-- Name: stock_inventory stock_inventory_product_id_key; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.stock_inventory
    ADD CONSTRAINT stock_inventory_product_id_key UNIQUE (product_id);


--
-- Name: stock_stockbatch stock_stockbatch_pkey; Type: CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.stock_stockbatch
    ADD CONSTRAINT stock_stockbatch_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_phone_c603acdd_like; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX accounts_user_phone_c603acdd_like ON public.accounts_user USING btree (phone varchar_pattern_ops);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: cart_cartitem_cart_id_370ad265; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX cart_cartitem_cart_id_370ad265 ON public.cart_cartitem USING btree (cart_id);


--
-- Name: cart_cartitem_product_id_b24e265a; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX cart_cartitem_product_id_b24e265a ON public.cart_cartitem USING btree (product_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: masters_brand_name_a83b2dda_like; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX masters_brand_name_a83b2dda_like ON public.masters_brand USING btree (name varchar_pattern_ops);


--
-- Name: masters_category_name_63286ae6_like; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX masters_category_name_63286ae6_like ON public.masters_category USING btree (name varchar_pattern_ops);


--
-- Name: masters_subcategory_category_id_c81cb1cd; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX masters_subcategory_category_id_c81cb1cd ON public.masters_subcategory USING btree (category_id);


--
-- Name: orders_order_coupon_id_5bddb887; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX orders_order_coupon_id_5bddb887 ON public.orders_order USING btree (coupon_id);


--
-- Name: orders_order_user_id_e9b59eb1; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX orders_order_user_id_e9b59eb1 ON public.orders_order USING btree (user_id);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: orders_orderitem_product_id_afe4254a; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX orders_orderitem_product_id_afe4254a ON public.orders_orderitem USING btree (product_id);


--
-- Name: products_product_brand_id_3e2e8fd1; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX products_product_brand_id_3e2e8fd1 ON public.products_product USING btree (brand_id);


--
-- Name: products_product_category_id_9b594869; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);


--
-- Name: products_product_name_fa23bcd2_like; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX products_product_name_fa23bcd2_like ON public.products_product USING btree (name varchar_pattern_ops);


--
-- Name: products_product_subcategory_id_b28a1e3b; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX products_product_subcategory_id_b28a1e3b ON public.products_product USING btree (subcategory_id);


--
-- Name: products_product_unit_id_07baa821; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX products_product_unit_id_07baa821 ON public.products_product USING btree (unit_id);


--
-- Name: promotions_coupon_code_92b1f2da_like; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX promotions_coupon_code_92b1f2da_like ON public.promotions_coupon USING btree (code varchar_pattern_ops);


--
-- Name: stock_stockbatch_product_id_acf1f3ec; Type: INDEX; Schema: public; Owner: instantuser
--

CREATE INDEX stock_stockbatch_product_id_acf1f3ec ON public.stock_stockbatch USING btree (product_id);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cart cart_cart_user_id_9b4220b9_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_user_id_9b4220b9_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_cart_id_370ad265_fk_cart_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_cart_id_370ad265_fk_cart_cart_id FOREIGN KEY (cart_id) REFERENCES public.cart_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_product_id_b24e265a_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_product_id_b24e265a_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_inventory inventory_inventory_product_id_5b835926_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.inventory_inventory
    ADD CONSTRAINT inventory_inventory_product_id_5b835926_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: masters_subcategory masters_subcategory_category_id_c81cb1cd_fk_masters_category_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.masters_subcategory
    ADD CONSTRAINT masters_subcategory_category_id_c81cb1cd_fk_masters_category_id FOREIGN KEY (category_id) REFERENCES public.masters_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_coupon_id_5bddb887_fk_promotions_coupon_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_coupon_id_5bddb887_fk_promotions_coupon_id FOREIGN KEY (coupon_id) REFERENCES public.promotions_coupon(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_user_id_e9b59eb1_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_user_id_e9b59eb1_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_product_id_afe4254a_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_product_id_afe4254a_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_brand_id_3e2e8fd1_fk_masters_brand_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_brand_id_3e2e8fd1_fk_masters_brand_id FOREIGN KEY (brand_id) REFERENCES public.masters_brand(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_category_id_9b594869_fk_masters_category_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_category_id_9b594869_fk_masters_category_id FOREIGN KEY (category_id) REFERENCES public.masters_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_subcategory_id_b28a1e3b_fk_masters_s; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_subcategory_id_b28a1e3b_fk_masters_s FOREIGN KEY (subcategory_id) REFERENCES public.masters_subcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_unit_id_07baa821_fk_masters_unit_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_unit_id_07baa821_fk_masters_unit_id FOREIGN KEY (unit_id) REFERENCES public.masters_unit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stock_inventory stock_inventory_product_id_87e1d4a4_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.stock_inventory
    ADD CONSTRAINT stock_inventory_product_id_87e1d4a4_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: stock_stockbatch stock_stockbatch_product_id_acf1f3ec_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: instantuser
--

ALTER TABLE ONLY public.stock_stockbatch
    ADD CONSTRAINT stock_stockbatch_product_id_acf1f3ec_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict IP8rkgbvOTyQbH8wi4cFP5eNX1sdKX196LbmIFfdbhka1AEgiNIHMBrGTheczSs

