[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:daphne]
command=daphne -b 0.0.0.0 -p 8080 config.asgi:application
autostart=true
autorestart=true
stderr_logfile=/tmp/daphne.err.log
stdout_logfile=/tmp/daphne.out.log

[program:celery]
command=celery -A config worker --loglevel=info
autostart=true
autorestart=true
stderr_logfile=/tmp/celery.err.log
stdout_logfile=/tmp/celery.out.log