[program:celery]
command=/app/.venv/bin/celery -A config worker --loglevel=info --pool=solo --concurrency=1
directory=/app
autostart=true
autorestart=true
stopwaitsecs=60
stderr_logfile=/tmp/celery.err.log
stdout_logfile=/tmp/celery.out.log