# Generated by Django 6.0.2 on 2026-06-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_advbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advbanner',
            name='image',
            field=models.ImageField(max_length=500, upload_to='advbanners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=500, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='categories/'),
        ),
    ]
