# Generated by Django 6.0.2 on 2026-05-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_driverattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverattendance',
            options={'ordering': ['-clock_in_time']},
        ),
        migrations.AlterUniqueTogether(
            name='driverattendance',
            unique_together=set(),
        ),
    ]
