# Generated by Django 6.0.2 on 2026-07-21 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_fcm_token'),
        ('store_picker', '0002_remove_storepickerprofile_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickers', to='store_picker.store'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('DELIVERY', 'Delivery Boy'), ('PICKUP', 'Pickup Boy')], max_length=20),
        ),
    ]
