# Generated by Django 6.0.2 on 2026-07-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_assigned_store_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_store',
        ),
    ]
