# Generated by Django 6.0.2 on 2026-07-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_picker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepickerprofile',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storepickerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='PickerAttendance',
        ),
        migrations.DeleteModel(
            name='StorePickerProfile',
        ),
    ]
