# Generated by Django 6.0.2 on 2026-08-14 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_at', models.TimeField(default=datetime.time(5, 30))),
                ('closes_at', models.TimeField(default=datetime.time(23, 0))),
                ('is_force_closed', models.BooleanField(default=False, help_text='Manual override — if on, store shows closed regardless of hours.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Schedule',
                'verbose_name_plural': 'Store Schedule',
            },
        ),
    ]
