# Generated by Django 6.0.2 on 2026-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_deliveryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='RAZORPAY', max_length=20),
        ),
    ]
