# Generated by Django 6.0.2 on 2026-06-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_method'),
        ('stock', '0002_stockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='stock.stockbatch'),
        ),
    ]
