# Generated by Django 6.0.2 on 2026-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_fee_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
