# Generated by Django 6.0.2 on 2026-07-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_cash_remitted_alter_order_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashremittance',
            old_name='submitted_at',
            new_name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='cashremittance',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='cashremittance',
            name='confirmed_by',
        ),
        migrations.AddField(
            model_name='cashremittance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_remittances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashremittance',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashremittance',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('DISCREPANCY', 'Discrepancy')], max_length=20),
        ),
    ]
