# Generated by Django 6.0.2 on 2026-04-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_brand_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/media/'),
        ),
    ]
