# Generated by Django 6.0.2 on 2026-06-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_flashsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
