# Generated by Django 6.0.2 on 2026-06-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
